### ISSUE TITLE
Pop-ups open under the navbar if the navbar is set to navbar-fixed-top

### ISSUE THREAD

**Issue by meertens** [mendix/MxBootswatch#5]
When pop-ups take more space (height) on the page than is available in the window, part of them disappears under the navbar if the navbar has class "navbar-fixed-top".

This seems to have two causes:
1. The z-index of the navbar is much heigher (1000+) than that of the pop-up (100+)
2. The position of the pop-up is partially under the navbar (always at 50% of the height of the navbar?)

Screenshot:
![pop-up under navbar](https://cloud.githubusercontent.com/assets/5245017/5529694/6e8800e0-8a17-11e4-858d-834044c9cd34.png)

**Comment by simo101** [comment]
This issue has now been fixed in the latest released version.

**Comment by meertens** [comment]
Thank you! The fix seems to work fine.

**Comment by simo101** [comment]
The new version will be available on the Mendix Appstore shortly.
