### ISSUE TITLE
Bootstrap version is out date

### ISSUE THREAD

**Issue by jugarin-golf** [mendix/MxBootswatch#6]
Hi Simon,
  I downloaded this layout and tried to change Glyphicon on sidebar toggle from justify to hamburger. I found that font icon was not up to date. So, can you please update the new version of bootstrap libraries/fonts in the next release?

Thank you in advance.
Jugarin Viboonsin

**Comment by simo101** [comment]
Thanks. I will schedule this for the next release.

**Comment by simo101** [comment]
Has now been implemented and will be released shortly to the appstore.
