### ISSUE TITLE
Mutli- Search for Enums / Data Grid Extender -- Spacelab

### ISSUE THREAD

**Issue by rickyv3** [mendix/MxBootswatch#7]
Hello,

We have run into an issue where it appears that the Spacelab CSS  is conflicting with out of the box Mx search functionality. The "multi-select" feature for enumerations within a data grid does not function properly when the enum / data grid utilized is not set at the top of the form, i.e. when the enum / data grid is accessed in a table midway or at the bottom of the form then the multi-parameter selection with pop-up at the top of the form rather than directly below the actual search parameter (see attached screenshots).

Steps to recreate:

1. Enable "Allow multi-select" for an enumeration search field
2. Attempt to utilize the search field for a enumeration that is toward the middle or bottom of the UI (i.e. where you have to scroll down to access it)
3. The search parameters will pop-up toward the middle or top of the UI, rather than directly below the input parameter

Note that this issue does not occur when the scroll bar is 100% to top, or where scrolling down on the page is not possible. It also does not appear to occur on the pop-up forms.

This also appears to be the case when attempting to utilize the Data Grid Extension widget. You cannot effectively utilize the "FlexHeader" setting within the widget within the Spacelab theme from any data grid that is NOT at the top of the UI.

Thank  you !
Rick
![themeissue1](https://cloud.githubusercontent.com/assets/13573078/10976709/e0ede22c-83b2-11e5-8b67-89e53e8d1019.png)
![themeissue2](https://cloud.githubusercontent.com/assets/13573078/10976708/e0ebe4a4-83b2-11e5-8472-88d42b4257bb.png)

**Comment by simo101** [comment]
Hi Ricky, Apologies for not getting back to you earlier. I was busy at a event Mendix was demonstrating at and was out of the country. It seems the issue you are facing are to do with the z-indexes of certain items. I will try to take a look at this soon. Do you need it fixed urgently or can it be fixed in a couple of weeks?

**Comment by rickyv3** [comment]
Hi Simon,

No problem. This is not urgent, so whenever you have time.

Thank you,

Ricky Volz

210.254.4988

**Comment by simo101** [comment]
Hi Ricky, I think you must be using an older version of spacelab. I tried to replicate your issue but couldn't. I think i fixed this in a previous version. In the meantime i have updated the styles to 5.21 and changed the example project to include the new radio buttons and layout grids. Please use the theme on the Github repo as I still need to update the appstore one.

**Comment by rickyv3** [comment]
Hi Simon,

Sorry for taking so long to get back to you - I was out on vacation for a
couple of weeks.

We have added quite a bit of custom styling added to the Spacelab theme,
esp. related to the log in page. We added some other aesthetic items along
the way, as well as a few stop gap fixes to address some of the bugs that I
believe you fixed in later iterations.

I was wondering, can I get around uploading the entire Spacelab package and
instead upload select items from the newest Spacelab package on github?
Have you updates / changes expanded to files beyond the following?: CSS
("bootstrap.min"), "index" and "index3" files? If not, I can pull out what
we added to these files, paste in your most recent iteration and then
reconcile the differences.

May be a dumb question but I am hoping to lessen the testing effort.

Thanks!


Ricky Volz
kinetech <http://kinetechcloud.com> *| *tel: 210.254.4988

**Comment by simo101** [comment]
You should put your custom styling in the custom.css rather than changing the bootstrap.min. if you then add the new bootstrap.min to your project and then add your custom css into the custom.css you should have all your styling. Does this make sense?

**Comment by rickyv3** [comment]
Are you referencing the 'mendix.custom' file as 'custom.css'?






Ricky Volz
kinetech <http://kinetechcloud.com> *| *tel: 210.254.4988

**Comment by rickyv3** [comment]
Hi Simon,

I have updated both the 'bootstrap' and 'bootstrap.min' files in my theme
with the most up to date files found on github for Spacelab (I then added
back the handful of statements we added back to the end of the
bootstrap.min file).

[image: Inline image 3]

I'm still running into the issues we had prior to updating the files,
namely:

- multi-search selection box does not align with search field associated
(i.e. it bounces all over page)
- radio buttons scroll with the page (we fixed this previously using CSS on
the actual cell / widget)
- search fields / reset features that do not seem to work any longer when
attempting to search over association - we just discovered this the other
day, and are not sure if it's theme or platform related yet
- data grid extension widget does not work for those data grids that we
part of tables below the top 50% of the page

I greatly appreciate any help you can offer,




Ricky Volz
kinetech <http://kinetechcloud.com> *| *tel: 210.254.4988
